# ==========================
# CONFIGURACI?N BASE DE DATOS H2 (CLIENTE)
# ==========================
# URL para una base de datos embebida en el directorio del usuario
URL_TEMPLATE=jdbc:h2:file:./chat_client_db_{USER_ID};DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
USER=sa
PASSWORD=
DRIVER=org.h2.Driver