# ==========================
# CONFIGURACION BASE DE DATOS
# ==========================
URL=jdbc:mysql://localhost:3307/server_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true
USER=server
PASSWORD=server
DRIVER=com.mysql.cj.jdbc.Driver

# ==========================
# CONFIGURACION SERVIDOR TCP
# ==========================
SERVER_PORT=9095
PEER_SERVER_PORT=6065
MAX_CONNECTIONS=4

# ==========================
# CONFIGURACIN VOSK
# ==========================
vosk.model.path=models/vosk-model-es-0.42