# ==========================
# CONFIGURACION BASE DE DATOS
# ==========================
URL=jdbc:mysql://localhost:3307/server_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true
USER=server
PASSWORD=server
DRIVER=com.mysql.cj.jdbc.Driver

# ==========================
# CONFIGURACION SERVIDOR TCP
# ==========================
SERVER_PORT=9095
PEER_SERVER_PORT=6065
MAX_CONNECTIONS=4

# ==========================
# CONFIGURACION API REST (HTTP)
# ==========================
# Puerto para el servidor HTTP REST (Javalin)
HTTP_PORT=8085

# ==========================
# CONFIGURACION API GATEWAY
# ==========================
# URL del API Gateway para registro de servidores
# Cambiar la IP a la del servidor donde corre el gateway
# Ejemplo para red local: http://192.168.1.X:5000/register-server
# Ejemplo para mismo equipo: http://localhost:5000/register-server
GATEWAY_URL=http://192.168.137.20:5000/register-server

# IP para registrarse en el gateway
# - host.docker.internal: Para pruebas locales (servidor y gateway en la misma máquina)
# - auto: Detecta automáticamente la IP local (para producción/múltiples máquinas)
# - IP específica: Puedes poner una IP manualmente (ej: 192.168.1.20)
GATEWAY_REGISTER_IP=192.168.137.200

# ==========================
# CONFIGURACIN VOSK
# ==========================
vosk.model.path=models/vosk-model-es-0.42