# ==========================
# CONFIGURACIÓN BASE DE DATOS
# ==========================
URL=jdbc:mysql://localhost:3306/server_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true
USER=root
PASSWORD=root
DRIVER=com.mysql.cj.jdbc.Driver

# ==========================
# CONFIGURACIÓN SERVIDOR TCP
# ==========================
SERVER_PORT=9090
MAX_CONNECTIONS=2